// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    type,
    payload
)
VALUES (
    $1,
    $2
)
RETURNING id, type, payload, status, attempts, created_at, updated_at
`

type CreateJobParams struct {
	Type    string
	Payload []byte
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.Type, arg.Payload)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
