// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
)

const claimPendingJob = `-- name: ClaimPendingJob :one
WITH next_job AS (
    SELECT id
    FROM jobs
    WHERE status = 'pending'
    AND (retry_at IS NULL OR retry_at <= NOW())
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE jobs
SET status = 'running', updated_at = NOW()
WHERE id = (SELECT id FROM next_job)
RETURNING id, type, payload, status, attempts, created_at, updated_at, retry_at
`

func (q *Queries) ClaimPendingJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRow(ctx, claimPendingJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    type,
    payload
)
VALUES (
    $1,
    $2
)
RETURNING id, type, payload, status, attempts, created_at, updated_at, retry_at
`

type CreateJobParams struct {
	Type    string
	Payload []byte
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.Type, arg.Payload)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, type, payload, status, attempts, created_at, updated_at, retry_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryAt,
	)
	return i, err
}

const getJobs = `-- name: GetJobs :many
SELECT id, type, payload, status, attempts, created_at, updated_at, retry_at 
FROM jobs
ORDER BY created_at DESC
`

func (q *Queries) GetJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetryAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingJob = `-- name: GetPendingJob :one
SELECT id, type, payload, status, attempts, created_at, updated_at, retry_at 
FROM jobs
WHERE status = 'pending'
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetPendingJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRow(ctx, getPendingJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryAt,
	)
	return i, err
}

const markJobCompleted = `-- name: MarkJobCompleted :exec
UPDATE jobs
SET status = 'completed', updated_at = NOW(), retry_at = NULL
where id = $1
`

func (q *Queries) MarkJobCompleted(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markJobCompleted, id)
	return err
}

const markJobFailed = `-- name: MarkJobFailed :exec
UPDATE jobs
SET status = 'failed', attempts = attempts + 1,  updated_at = NOW()
where id = $1
`

func (q *Queries) MarkJobFailed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markJobFailed, id)
	return err
}

const markJobRunning = `-- name: MarkJobRunning :exec
UPDATE jobs
SET status = 'running', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkJobRunning(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markJobRunning, id)
	return err
}

const scheduleRetry = `-- name: ScheduleRetry :exec
UPDATE jobs
SET status = 'pending', 
    retry_at = NOW() + INTERVAL '10 seconds',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ScheduleRetry(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, scheduleRetry, id)
	return err
}
