// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID        int64
	Type      string
	Payload   []byte
	Status    string
	Attempts  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	RetryAt   pgtype.Timestamp
}
